# Generated by Django 4.2.6 on 2023-10-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='is_show',
        ),
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='菜单标题'),
        ),
        migrations.AddField(
            model_name='permission',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='描述'),
        ),
    ]
