# Generated by Django 4.2.6 on 2023-10-19 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_menu_is_show_menu_title_permission_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.menu', verbose_name='父菜单'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=30, verbose_name='权限名'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('name', 'method')},
        ),
    ]
