# Generated by Django 4.2.6 on 2023-10-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disabled_permission',
            field=models.ManyToManyField(blank=True, to='system.permission', verbose_name='禁用的权限'),
        ),
    ]
