# Generated by Django 4.2.6 on 2023-10-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_user_disabled_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='component',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_frame',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='path',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='pid',
        ),
    ]
