# Generated by Django 4.2.6 on 2023-10-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_remove_menu_component_remove_menu_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='sort',
        ),
    ]
