# Generated by Django 4.2.6 on 2023-10-28 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_remove_menu_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='pid',
        ),
        migrations.AddField(
            model_name='menu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.menu', verbose_name='父菜单'),
        ),
    ]
